language: java
jdk:
  - oraclejdk8

script:
  - ./gradlew build

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew data-weave-plugin:publishPlugin
    on:
      branch: master


notifications:
  slack: mulesoft:IqbP7oSC8usH82K9o2p5TOjT